export interface IProduct{
    id: number,
    description: string,
    brand: string,
    idCategories: string[],
    priority: number,
    visible: boolean,
    price: number,
    iva: number,
    discount1: number | null,
    discount2: number | null,
    discount3: number | null,
    updatedAt: Date,
    urlImg: string,
    inStock: boolean,
    quantity?: number,
    tags: string[],
    showInHeroCarousel: boolean,
}